#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cp /data/web/vimbadmin/public/.htaccess.dist /data/web/vimbadmin/public/.htaccess

echo "vimbadmin environment variable substitution"
sed \
-e "s/^resources.doctrine2.connection.options.dbname.*/resources.doctrine2.connection.options.dbname = '${VIMBADMIN_DB_NAME}'/" \
-e "s/^resources.doctrine2.connection.options.user.*/resources.doctrine2.connection.options.user = '${VIMBADMIN_DB_USER}'/" \
-e "s/^resources.doctrine2.connection.options.password.*/resources.doctrine2.connection.options.password = '${VIMBADMIN_DB_PASSWORD}'/" \
-e "s/^resources.doctrine2.connection.options.host.*/resources.doctrine2.connection.options.host = '${VIMBADMIN_DB_HOST}'/" \
-e "s/^server.email.address.*/server.email.address = '${ADMIN_EMAIL}'/" \
-e "s/^resources.mail.transport.host.*/resources.mail.transport.host = '${SMTP_HOST}'/" \
-e "s/^defaults.mailbox.password_scheme.*/defaults.mailbox.password_scheme = 'crypt:sha512'/" \
    /data/web/vimbadmin/application/configs/application.ini.dist > /data/web/vimbadmin/application/configs/application.ini 
